#ifndef QQTSOFTKEYBOARD_GLOBAL_H
#define QQTSOFTKEYBOARD_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef Q_OS_WIN
#if defined(QQTSOFTKEYBOARD_LIBRARY)
#  define QQTSOFTKEYBOARDSHARED_EXPORT Q_DECL_EXPORT
#elif defined(QQTSOFTKEYBOARD_STATIC_LIBRARY)
#  define QQTSOFTKEYBOARDSHARED_EXPORT
#else
#  define QQTSOFTKEYBOARDSHARED_EXPORT Q_DECL_IMPORT
#endif
#else
#  define QQTSOFTKEYBOARDSHARED_EXPORT
#endif

#endif // QQTSOFTKEYBOARD_GLOBAL_H
