#ifndef QSOFTKEYBOARD_GLOBAL_H
#define QSOFTKEYBOARD_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef Q_OS_WIN
#if defined(QSOFTKEYBOARD_LIBRARY)
#  define QSOFTKEYBOARDSHARED_EXPORT Q_DECL_EXPORT
#elif defined(QSOFTKEYBOARD_STATIC_LIBRARY)
#  define QSOFTKEYBOARDSHARED_EXPORT
#else
#  define QSOFTKEYBOARDSHARED_EXPORT Q_DECL_IMPORT
#endif
#else
#  define QSOFTKEYBOARDSHARED_EXPORT
#endif

#endif // QSOFTKEYBOARD_GLOBAL_H
